- README.md
I've only been able to add the Issue tracking badge. The rest have some issues
> (GitHub): Code Quality Badges

- client/package-lock.json
- client/package.json
- infrastructure/bin/infrastructure.ts
- infrastructure/lib/infrastructure-stack.ts
- infrastructure/package-lock.json
- infrastructure/package.json
1. I've added the S3 Bucket which holds our React Application
2. Add the stack where the bucket will live
3. Hosting is up and running
> ✨ (hosting): CDK Hosting Added

- client/package-lock.json
- client/package.json
- client/postcss.config.js
- client/src/App.tsx
- client/src/css/index.css
- client/tailwind.config.js
Tailwindcss files added for styling purposes
> 📦 Added styling files (Tailwindcss)

- .github/workflows/frontend.yml
- client/package.json
- client/postcss.config.js
Removed matrix strategy from workflow file
> 🔥 (CICD): Minor changes to React worfklow file

- client/.prettierrc.json
- client/src/mock.json
Added mock data files and also fixed a bug
> 🐛 🤡 (UI): Added mock data files and also fixed a bug

- client/src/components/CLReports/CLReports.tsx
- client/src/components/Drafts/Drafts.tsx
- client/src/components/Explore/Explore.tsx
- client/src/components/Home/Home.tsx
- client/src/components/Landing/Landing.tsx
- client/src/components/Navigation/Navigation.tsx
- client/src/components/Profile/Profile.tsx
- client/src/components/Reports/Reports.tsx
- client/src/components/Shared/Shared.tsx
Added buttons to the Navigation and converted them to New Components
> 🚸 💄 🎨 (UI): Added buttons to the Navigation

- client/package-lock.json
- client/package.json
- client/src/components/GenReport/GenReport.tsx
- client/src/components/Home/Home.tsx
- client/src/components/Landing/Landing.tsx
Added functionality to allow users to generate reports based on search.
> ✨ Added Mock generate report functionality

- client/package-lock.json
- client/public/index.html
Added Logo to title bar and also update the title
> 🚸 💄 ⚡️ 🎨 (UI): Added Logo to title bar and also update the title

- client/package-lock.json
- client/src/components/Explore/Explore.tsx
- client/src/components/GenReport/GenReport.tsx
- client/src/components/Home/Home.tsx
- client/src/components/Home/__tests__/Home.test.tsx
- client/src/components/Landing/Landing.tsx
- client/src/components/Navigation/Navigation.tsx
- client/src/components/Reports/Reports.tsx
Finished tests for home components
> 33 unit testing

- client/src/components/Reports/Reports.tsx
- client/src/components/Reports/__tests__/Reports.test.tsx
Report component testing 6 Tests added
> ✅ merging working Tests for report component: working

- client/src/components/Home/__tests__/Home.test.tsx
- client/src/components/Landing/Landing.tsx
- client/src/components/Landing/__tests__/Landing.test.tsx
- client/src/components/Login/Login.tsx
- client/src/components/Login/__tests__/Login.test.tsx
- client/src/components/Logo/Logo.tsx
- client/src/components/Logo/__tests__/Logo.test.tsx
- client/src/components/Reports/__tests__/Reports.test.tsx
- client/src/components/Signup/Signup.tsx
- client/src/components/Signup/__tests__/Signup.test.tsx
> ✅ :merging working Tests for other component: working

- README.md
> Changing Picture

- client/src/App.tsx
- client/src/components/Landing/Landing.tsx
- client/src/components/Login/Login.css
- client/src/components/Login/Login.tsx
- client/src/components/Navigation/Navigation.tsx
- client/src/mock.json
Added the Login Component Functionality
> 🚸 🚧 🚀 ⚡️ 🎨 ✨ (UI): Added the Login Component Functionality

- client/src/App.tsx
Fixed authentication issues to accomodate either email or username
> 🚑 (UI) : Fixed authentication issues to accomodate either email or username

- client/src/App.tsx
- client/src/components/Signup/Signup.css
- client/src/components/Signup/Signup.tsx
> 🚸 🚧 🚀 ⚡️ 🎨 ✨(UI): Added the Signup Component

- client/src/components/Login/Login.tsx
- client/src/components/Login/__tests__/Login.test.tsx
- client/src/components/Signup/Signup.tsx
- client/src/components/Signup/__tests__/Signup.test.tsx
Basic unit testing of components of the login and sign up pages.
> ✅ Added basic render and input field unit tests for login and sign up components

- client/src/components/Home/Home.tsx
Interface for generate report webpage generated
> 🚸 🚧 🚀 ⚡️ 🎨 ✨(UI): Interface for generate report webpage generated

- client/src/components/Explore/Explore.tsx
- client/src/components/Home/Home.tsx
- client/src/components/Landing/Landing.tsx
- client/src/components/Logo/Logo.tsx
- client/src/components/Navigation/Navigation.tsx
- client/tailwind.config.js
Added a little bit of responsiveness
> 🚸 💄 (UI): Added a little bit of responsiveness

- client/README.md
- serverless.ts
New hosting has been setup using serverless framework and cloudfront
> 🔥 ✨ (CICD): Hosting up and running

- .github/workflows/main.yml
- .github/workflows/serverless-deploy.yml
Missing tests for serverless so cant do any cicd tests
> ✨ (CICD): Full workflow 80% complete

- client/src/components/Home/Home.tsx
Adjusting the filter and sorting options
> 🚑  (UI): adjusting the filter and sorting options

- .github/workflows/serverless-deploy.yml
- README.md
Added the badges for the builds and refactored the README.
Changed the workflow name
> ✨ (CICD): Made changes to README & workflow name

- client/src/components/Home/Home.tsx
> ⚡️ (UI): Adding default select options

- client/src/components/Home/Home.tsx
- client/src/components/Home/__tests__/Home.test.tsx
Added some basic render unit tests for Home page components
> ✅ Added unit tests for Home Page

- client/package.json
- client/src/components/GenReport/GenReport.tsx
- client/src/components/Home/Home.tsx
- client/src/components/Landing/Landing.tsx
- client/src/components/Navigation/Navigation.tsx
- client/src/components/PageNotFound/PageNotFound.tsx
- client/yarn.lock
Added proper react routing between different navigation components in the landing page
> ✨ Added react routing to landing page

- README.md
The requires.io badge is the only badge missing. Their website seems to be broken
> 🔥 ✨ (CICD): Added new badges & refactored code

- babel.config.js
- jest.int.config.js
- jest.unit.config.js
- package.json
- serverless.ts
- src/model/database.ts
- src/model/resultSet/index.ts
- src/model/resultSet/resultSet.model.ts
- src/services/__tests__/creator.service.int.ts
- src/services/creator.service.ts
- src/services/resultSet.service.ts
- yarn.lock
New table ResultSetTable has been created. In this PR there are scripts for integration testing for the CreatorsTable. All are currently failing because they timeout. Please take a look to see how it can be improved and I'll do the same.
> ✨ 🗃️ 🔧 ➕ result set table creation 

- client/src/components/Landing/Landing.tsx
- client/src/components/Navigation/Navigation.tsx
Added the logout functionality
> ✨ (UI): Added the logout functionality

- client/src/App.tsx
- client/src/components/Home/Home.tsx
- client/src/components/Landing/Landing.tsx
Added a new functionality that keeps you on the page even if you refresh as long as you haven't logged out
> ✨ 🎨 ⚡️ (UI): Added a new functionality

- client/package.json
- client/src/components/GenReport/GenReport.tsx
- client/src/components/Home/Home.tsx
- client/src/components/Text/Text.tsx
- client/src/components/Tweet/Tweet.tsx
- client/src/editReport.json
- client/yarn.lock
- package.json
- yarn.lock
Added new component called text and also created the text editor
> 💄 ✨ ⚡️ 🎨 (UI): Added new component called text

- src/functions/search/handler.ts
added cors headers to allow it to function properly
> ✨Added in course header

- client/src/components/History/History.tsx
- client/src/components/Landing/Landing.tsx
- client/src/components/Navigation/Navigation.tsx
Added the History page to the navigation
> 🚧 💄 ✨ 🎨 (UI): Added the History page to the navigation

- src/functions/creator/index.ts
- src/functions/search/index.ts
- src/functions/trending/index.ts
This should fix the CORS issues
> ✨ (API): Aded CORS to HTTP

- client/src/App.tsx
- client/src/components/GenReport/GenReport.tsx
- client/src/components/Home/Home.tsx
- client/src/components/Landing/Landing.tsx
- client/src/components/Login/Login.tsx
- client/src/components/Navigation/Navigation.tsx
- client/src/components/Signup/Signup.tsx
- client/src/components/Tweet/Tweet.tsx
- client/src/index.tsx
Linked frontend with api {mock data replaced with live data}
> 💄 ✨ ⚡️ 🎨 (UI): Linked frontend with api 

- client/src/App.tsx
- client/src/components/Home/Home.tsx
- client/src/components/Landing/Landing.tsx
- client/src/components/Login/Login.tsx
- client/src/components/Signup/Signup.tsx
Login and signup endpoint added
> 💄 ✨ 🎨 ⚡️(UI): Login and signup endpoint added

- client/src/components/Home/Home.tsx
> 💄 ✨ ⚡️ 🎨(UI): Added endpoint to Search

- client/src/App.tsx
- client/src/components/Landing/Landing.tsx
- client/src/components/Login/Login.tsx
- client/src/components/Signup/Signup.tsx
- client/src/components/Splash/Splash.tsx
All page components consist of proper routing
> ✨ Fixed Routing for all components

- client/src/components/GenReport/GenReport.tsx
- client/src/components/Home/Home.tsx
- client/src/components/Landing/Landing.tsx
Linked Gen Report page with endpoint
> 💄 ✨ ⚡️ 🎨(UI): Linked Gen Report page with endpoint

- serverless.ts
- src/model/reportBlock/index.ts
- src/model/reportBlock/reportBlock.model.ts
- src/services/reportBlock.service.ts
New table ReportBlockTable will be created
> ✨ 🗃️ 🔧 (DB) add report block table

- src/model/reportBlock/reportBlock.model.ts
- src/services/reportBlock.service.ts
> 🗃️ ✏️ (DB) change to report block model

- serverless.ts
- src/model/report/report.model.ts
- src/model/textStyles/index.ts
- src/model/textStyles/textStyles.model.ts
- src/services/reportBlock.service.ts
Added new function to ReportBlockTable
> ✨ 🗃️ 🔧  add new table TextStylesTable

- client/src/components/History/History.tsx
- client/src/components/HistoryCard/HistoryCard.tsx
- client/src/components/Home/Home.tsx
Created History card component and passed div into it
> ✨ (UI): Created History card component and passed div into it

- client/src/App.tsx
- client/src/components/History/History.tsx
- client/src/components/HistoryCard/HistoryCard.tsx
- client/src/components/Home/Home.tsx
- client/src/components/Landing/Landing.tsx
- client/src/components/Login/Login.tsx
- client/src/components/Signup/Signup.tsx
- client/src/components/ViewHistory/ViewHistory.tsx
Changed the some endpoints for Team members testing
> 🚑 (UI): Changed the some endpoints for Team members testing

- src/services/__tests__/creator.service.spec.ts
- src/services/__tests__/report.service.spec.ts
- src/services/report.service.ts
- src/services/reportBlock.service.ts
There are 9 unit tests in total
> ✅ add unit tests for Creator and Report tables

- client/src/components/DraftCard/DraftCard.tsx
- client/src/components/Drafts/Drafts.tsx
- client/src/components/History/History.tsx
- client/src/components/Home/Home.tsx
Retrieving data from API and Created new components
> ✨ (UI): Retrieving data from API and Created new components

- client/src/components/GenReport/GenReport.tsx
- client/src/components/Text/Text.tsx
- client/src/components/Tweet/Tweet.tsx
Retreiving data from Get Report API
> ✨ (UI): Retreiving data from Get Report API

- client/src/components/Drafts/Drafts.tsx
- client/src/components/Home/Home.tsx
- client/src/components/Landing/Landing.css
- client/src/components/Landing/Landing.tsx
- client/src/components/Login/Login.tsx
- client/src/components/MobileNavigation/MobileNavigation.tsx
Mobile Navigation Added with Style
> ✨💄(UI): Mobile Navigation Added with Style

- client/src/components/GenReport/GenReport.tsx
Fixed margin issues on gen report page
> 🚑 (UI): Fixed margin issues on gen report page

- src/functions/report/handler.ts
- src/model/report/report.model.ts
- src/services/__tests__/report.service.spec.ts
Added status attribute to report model to know the status of report (draft, published, deleted).
> :construction: :card_file_box: add attribute to report model

- src/services/report.service.ts
The status of a report can now be updated. This enables publishing and deleting of a report.
> ✨ 🗃️ (DB) Add update function for report status attribute

- src/services/resultSet.service.ts
Result sets can now be deleted.
> ✨ 🗃️ (DB) Add delete operation for a result set

- src/functions/report/handler.ts
- src/functions/resources/APIresponse.ts
Gives a more meaningful message for errors. Also added in centralised return status codes.
> 🐛 ⚡ 🧑‍💻  Improved API response headers for errors in report

- client/src/components/Home/Home.tsx
- client/src/components/Text/Text.tsx
Fixed text editor logical error
> 🚑 (UI): Fixed text editor logical error

- client/src/components/HistoryCard/HistoryCard.tsx
- client/src/components/Landing/Landing.tsx
- client/src/components/Text/Text.tsx
> ⚡️ (UI): added delete icon

- client/src/App.tsx
- client/src/components/HistoryCard/HistoryCard.tsx
- client/src/components/Home/__tests__/Home.test.tsx
- client/src/components/HomeTweet/HomeTweet.tsx
- client/src/components/Landing/Landing.tsx
- client/src/components/Login/__tests__/Login.test.tsx
- client/src/components/Signup/Signup.tsx
- client/src/components/Signup/__tests__/Signup.test.tsx
- client/src/components/Text/Text.tsx
- client/src/components/Tweet/Tweet.tsx
Updated code to contain camel case for all variables and fixed buttons with missing button types.
> 🎨 (UI): Updated variables to camelCase in all variables and added types to buttons

- src/functions/creator/handler.ts
- src/services/__tests__/creator.service.spec.ts
- src/services/creator.service.ts
Credential checks are now done in the lambda functions.
> 🔥 🗃️ ✅ (DB/SERV) Remove credential checks from creator service

- src/services/report.service.ts
@malcolmdzimati I've added a function that will fetch draft reports only for the Draft page. Tell me if this is fine.
> ✨ 🗃️ (DB) Add function to get draft reports

- src/functions/creator/handler.ts
- src/functions/report/handler.ts
- src/functions/reportBlock/handler.ts
- src/services/report.service.ts
- src/services/textStyles.service.ts
@Ivy-leet Please review and merge.
@Ivy-leet please also do be a favor a test the clone report ID, it should:
- clone the report
- clone the blocks
- clone the text and tweets
this is just the proposed function this will definitly change after we discuss with the mentors and amongst ourselves some key concerns I have, and I think we have to restructure our tweet to resultset relationship within the system and database.
request body:
- reportID
- apiKey
- author
> ✨(SERV) Added function code for report cloning

- src/services/permission.service.ts
Functions added are:
- getPermissions
- updatePermission
- deletePermission
> ✨ ✏️ 🗃️ (DB) Add more operations for permission table

- client/src/App.tsx
- client/src/components/Login/Login.tsx
- client/src/components/Signup/Signup.tsx
- client/src/resources/links.json
Made changes to endpoint link format
> 🎨 (UI): Made changes to endpoint link format

- client/src/components/DraftCard/DraftCard.tsx
- client/src/components/Drafts/Drafts.tsx
- client/src/components/History/History.tsx
- client/src/components/HistoryCard/HistoryCard.tsx
- client/src/components/Home/Home.tsx
- client/src/components/Landing/Landing.tsx
Added delete Icon to Resultset and Drafts
> ✨ (UI): Added delete Icon to Resultset and Drafts

- client/src/components/GenReport/GenReport.tsx
- client/src/components/HistoryCard/HistoryCard.tsx
Improved tweet component and updated endpoints
> ✨ 🎨 (UI): Improved tweet component and updated endpoints

- src/functions/resultSet/handler.ts
- src/services/resultSet.service.ts
Key attribute missing from the delete operation.
> 🗃️  🚑 (DB) Fix to delete result set function

- client/src/components/GenReport/GenReport.tsx
- client/src/components/Home/Home.tsx
- client/src/components/Shared/Shared.tsx
> 💄 ✨ ⚡️ (UI): Sharing Report Successful

- .github/workflows/build.yml
Reverts COS301-SE-2022/Twitter-Summariser#452
> Revert "💚 ✨(CICD): Testing to see if options worked"

- client/src/components/GenReport/GenReport.tsx
Added options to Sharing Report
> ⚡️ (UI): Added options to Sharing Report

- client/src/components/Button/Button.tsx
- client/src/components/Home/Home.tsx
- client/src/components/Landing/Landing.tsx
- client/src/components/Login/Login.tsx
- client/src/components/Navigation/Navigation.tsx
Added loading feedback to Search and Generate functionality
> 💄(UI): Added loading feedback to Search and Generate functionality

- client/package.json
- client/public/index.html
- client/src/components/DraftCard/DraftCard.tsx
- client/src/components/Drafts/Drafts.tsx
- client/yarn.lock
Added loader feedback and animation for draft page
> 💄 (UI): Added loader feedback and animation for draft page

- client/src/components/Explore.tsx
- client/src/components/ExploreCard.tsx
- client/src/components/GenReport.tsx
- client/src/components/Shared.tsx
Added loading screen and animation for explore
> 💄 (UI): Added loading screen and animation for explore

- client/src/components/ReportCard.tsx
- client/src/components/Reports.tsx
Added loading feedback and animation to Report Page
> 💄 (UI): Added loading feedback and animation to Report Page

- serverless.ts
- src/model/schedule/index.ts
- src/model/schedule/schedule.model.ts
- src/services/index.ts
- src/services/schedule.service.ts
Table to store schedule report settings is added. @malcolmdzimati The model contains comments of what which attribute means. Can be changed as time goes on.
> ✨ 🗃️ 🔧 🚧 (DB) Add new schedule settings table

- client/src/components/History.tsx
- client/src/components/Home.tsx
- client/src/components/Shared.tsx
- client/src/components/SharedCard.tsx
- client/src/components/ViewHistory.tsx
- [💄 (UI): I just fixed a little word error](https://github.com/COS301-SE-2022/Twitter-Summariser/commit/0de99343b8769dbe96c533e809e785189f8958de)
- [Merge branch 'develop' of](https://github.com/COS301-SE-2022/Twitter-Summariser/commit/04a9caa43f312ac97fb21a5f7a5c01af8b9c4782) [https://github.com/COS301-SE-2022/Twitter-S…](https://github.com/COS301-SE-2022/Twitter-Summariser)
- [💄 (UI): Added loading screen for feedback and animation for the share…](https://github.com/COS301-SE-2022/Twitter-Summariser/commit/7402f9c8f1713fd2fbf8246870307d1bb2179bc3)
- [💄 (UI): Tried maintaining consistency accross all pages including Vie…](https://github.com/COS301-SE-2022/Twitter-Summariser/commit/5744c189db5f63783e8761defbccb8445fc21689)
- [💄 (UI): Applied (initial diabled Generate button next to …
> 💄 (UI): See lists of commits in the comment

- src/services/reportBlock.service.ts
A function to update the position of a report block called updatePosition.
> ✨ 🗃️ (DB) Add update function for report block

- src/services/textStyles.service.ts
Added function to delete text styles which will be relevant when deleting text from a report.
> ✨ 🗃️ (DB) Add function to delete text style

- client/src/components/Home.tsx
Update number of tweets - maybe 5, 10, 15
> 💄 (UI): Update number of tweets - maybe 5, 10, 15

- client/src/components/GenReport.tsx
- client/src/components/GetPublishedReport.tsx
- client/src/components/Home.tsx
- client/src/components/scroll/ScrollToTop.tsx
- client/src/pages/Landing.tsx
- client/src/utils/classNames.tsx
- [💄 (UI): DEMO: Add skeleton loader for when lots of tweets are loading…]
- [💄 (UI): DEMO: Add button to return to top as you scroll (on all pages)]
> 💄(UI): Please find the list of commits made in the comment

- client/src/components/GenReport.tsx
- client/src/components/GetPublishedReport.tsx
- client/src/components/Home.tsx
- client/src/components/ViewHistory.tsx
- [💄 (UI): TASKS: Update genReport card (Home page)]
- [💄 (UI): TASKS: Update genReport card (View History page)]
- [💄 (UI): DEMO: Add skeleton loader for when lots of tweets are loading…]
- [💄 (UI): Made the page look more elegant]
- [💄 (UI): Fixed publish report Glitch]
- [💄 (UI): Fixed generate report Glitch]
>  💄(UI): Please find the list of commits made in the comment

- src/services/__tests__/permission.service.spec.ts
- src/services/creator.service.ts
Included in this pr is a unit test for the permission service.
> ✨ 🗃️ ✅ (DB) Add function to delete creator  

- app/client/yarn.lock
- app/serverless.ts
- app/src/functions/tweet/handler.ts
@malcolmdzimati @Ivy-leet Please make sure that if the function declaration is async you put the await keyword on the function call.
> 🐛 🚑 (API): Fixed generate report issue

- app/client/src/components/GenReport.tsx
This is a temporary solution until the response from the API sends back the correct user permissions for a particular report
> 🐛 ✨ (UI): Temporary fix to add permissions to viewing draft reports

- app/client/src/components/Modal.tsx
Fully implemented adding of custom tweets from frontend. Should work with no bugs once fix has been made from backend.
> ✨ (UI): Added code to add custom tweets from frontend

- app/client/src/components/GenReport.tsx
Added code to delete tweets in draft reports. Needs testing once relevant fixes are made from backend hence currently commented out
> ✨ (UI): Added code to delete tweets in draft reports

- app/client/src/App.tsx
- app/client/src/index.tsx
Refactoring code to contain file descriptions and comments to explain code functionality
> 🗑️ ♻️ (UI): CODE CLEANUP - Adding relevant descriptions and comments to Index and App component files

- app/client/package.json
- app/client/src/components/Home.tsx
Added temporary solution to query API to schedule report. Needs testing and will be finalized once new schedule report component has been added and backend has finalized relevant attributes needed in the request of the API call. Currently commented out until abovementioned matters have been resolved.
>  ✨ (UI): Added code to query API to schedule report with temporary components

- app/client/public/index.html
- app/client/src/components/AdvanceSearch.tsx
- app/client/src/components/Home.tsx
- app/client/src/components/Profile.tsx
- app/client/src/components/styles/Profile.css
Waiting for a quick meeting with Jonah to integrate the schedule feature for the advance search
Waiting for a quick meeting with JJ to integrate the upload profile picture feature
> 💄(UI): Advance search property and image upload feature for profile added and 80% ready. 

- app/src/functions/schedulers/index.ts
- app/src/services/report.service.ts
Anyone please accept and merge, @jonahgasura  if you merge it, try check if this fixes that textblock issue
> ⚡ 🐛 (API/SERV) Fix for gen report and removing autherizer

- app/client/src/App.tsx
- app/client/src/components/DraftCard.tsx
- app/client/src/components/DraftReport.tsx
- app/client/src/components/ExploreCard.tsx
- app/client/src/components/Home.tsx
- app/client/src/components/Report.tsx
- app/client/src/components/ReportCard.tsx
- app/client/src/components/ViewHistory.tsx
Removed use of local storage to keep track of current reports
> ⚡️✨(UI): Updated routing to draft and published report pages to include report IDs in the URL

- app/client/src/App.tsx
- app/client/src/components/DraftCard.tsx
- app/client/src/components/Home.tsx
- app/client/src/components/Report.tsx
- app/client/src/components/SharedCard.tsx
- app/client/src/components/ViewHistory.tsx
Updated report component to render both draft and published reports depending on state of report being either "DRAFT" or "PUBLISHED".
@GO-Shoderu please take note of this whenever you wish to make any changes to draftReport it should now all be done in the Report component
> ⚡️✨(UI): Moved all draft report functionality to single report component

- app/client/package.json
- app/client/src/components/AdvanceSearch.tsx
- app/client/src/components/Home.tsx
- app/client/src/components/Report.tsx
- app/client/src/components/SharedCard.tsx
Implemented functionality to make API call to schedule a report. @Ivy-leet please note that I have not linked it to an issue yet as once testing is complete from backend I will do a final clean up of the code once everything is fully integrated and then close the relevant issues when that is complete.
> ✨ (UI): Added code to query API to schedule report from frontend

- app/src/functions/backup/index.ts
- app/src/functions/schedulers/handler.ts
Hopefully this will also deploy changes of backupDynamoDB
> 🔥 Change ARN of lambda function

- app/src/functions/report/handler.ts
- app/src/functions/schedulers/handler.ts
Reverts COS301-SE-2022/Twitter-Summariser#808
> Revert "(API/SERV)🐛 fix for schedual report"

- app/src/services/__tests__/report.service.spec.ts
- app/src/services/report.service.ts
Reverts COS301-SE-2022/Twitter-Summariser#809
> Revert "🐛  🗃️  Stop dynamodb from overriding"
